/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author YisuCrist
 */
public class MyPanel extends javax.swing.JPanel {

    ImageIcon cara = new ImageIcon(getClass().getResource("m.png"));
//    abeja a = new abeja(10, 100);
//    abeja a1 = new abeja(20, 600);
//    abeja a2 = new abeja(500, 108);
//    abeja a3 = new abeja(60, 400);
//    abeja a4 = new abeja(115, 300);
//    abeja a5 = new abeja(265, 273);
//    abeja a6 = new abeja(0, 0);
//    abeja a7 = new abeja(300, 600);

    public void paintComponent(Graphics g) {
        super.paintComponent(g);

        //Call this shit motherfucker
        main.popo();

        ArrayList<abeja> cantidad = new ArrayList<>();

        Image ima = cara.getImage();

        double maxX = Double.MIN_VALUE;
        double maxY = Double.MIN_VALUE;

        //Conseguir maxima coordenada
        for (Collision coli : QuadTree.colisioncitas) {
            if (coli.getFirst().getX() > maxX) {
                maxX = coli.getFirst().getX();
            }
            if (coli.getSecond().getX() > maxX) {
                maxX = coli.getSecond().getX();
            }

            if (coli.getFirst().getY() > maxY) {
                maxY = coli.getFirst().getY();
            }
            if (coli.getSecond().getY() > maxY) {
                maxY = coli.getSecond().getY();
            }
        }

        //COnvertir coordenada en Pixel y pintar
        for (Collision coli : QuadTree.colisioncitas) {
            double primerX = Math.abs(coli.getFirst().getX());
            double primerY = Math.abs(coli.getFirst().getY());

            double secondX = Math.abs(coli.getSecond().getX());
            double secondY = Math.abs(coli.getSecond().getY());

            double primerPixelX = (60 * primerX) / maxX;
            double primerPixelY = (60 * primerY) / maxY;
            double secondPixelX = (60 * secondX) / maxX;
            double secondPixelY = (60 * secondY) / maxY;

            System.out.println("#######");
            System.out.println(primerPixelX);
            System.out.println(primerPixelY);
            System.out.println(secondPixelX);
            System.out.println(secondPixelY);
            g.drawImage(ima, (int) primerPixelX, (int) primerPixelY, this);
            g.drawImage(ima, (int) secondPixelX, (int) secondPixelY, this);
        }
//
//        cantidad.add(a);
//        cantidad.add(a1);
//        cantidad.add(a2);
//        cantidad.add(a3);
//        cantidad.add(a4);
//        cantidad.add(a5);
//        cantidad.add(a6);
//        cantidad.add(a7);
//
//        
//        float x = a.getCoordenadaX();
//        float y = a.getCoordenadaY();
//        g.drawImage(ima, (int) x, (int) y, this);
//
//        float x1 = a1.getCoordenadaX();
//        float y1 = a1.getCoordenadaY();
//        g.drawImage(ima, (int) x1, (int) y1, this);
//
//        float x2 = a2.getCoordenadaX();
//        float y2 = a2.getCoordenadaY();
//        g.drawImage(ima, (int) x2, (int) y2, this);
//
//        float x3 = a3.getCoordenadaX();
//        float y3 = a3.getCoordenadaY();
//        g.drawImage(ima, (int) x3, (int) y3, this);
//
//        float x4 = a4.getCoordenadaX();
//        float y4 = a4.getCoordenadaY();
//        g.drawImage(ima, (int) x4, (int) y4, this);
//
//        float x5 = a5.getCoordenadaX();
//        float y5 = a5.getCoordenadaY();
//        g.drawImage(ima, (int) x5, (int) y5, this);
//
//        float x6 = a6.getCoordenadaX();
//        float y6 = a6.getCoordenadaY();
//        g.drawImage(ima, (int) x6, (int) y6, this);
//
//        float x7 = a7.getCoordenadaX();
//        float y7 = a7.getCoordenadaY();
//        g.drawImage(ima, (int) x7, (int) y7, this);

    }

    public static void main(String[] args) {

        JOptionPane.showMessageDialog(null, "Comencemos");
        MyPanel j = new MyPanel();
        JFrame jf = new JFrame();
        jf.setTitle("colision de abejas");
        jf.setSize(400, 400);
        jf.setVisible(true);
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.add(j);

    }

    /**
     * Creates new form MyPanel
     */
    public MyPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
